[tool.poetry]
name = "options-advisor"
version = "0.1.0"
description = ""
authors = ["omdv <omdv@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.10"
flask = "^3.0.3"
pandas = "^2.2.2"
yfinance = "^0.2.38"
jinja2 = "^3.1.3"
matplotlib = "^3.8.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
