[tool.poetry]
name = "options-advisor"
version = "0.1.0"
description = ""
authors = ["omdv <omdv@protonmail.com>"]
readme = "README.md"

[tool.poetry.group.main.dependencies]
python = "3.10.10"
pandas = "^2.2.2"
jinja2 = "^3.1.3"
matplotlib = "^3.8.4"
seaborn = "^0.13.2"
boto3 = "^1.34.101"



[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.2.0"
flask = "^3.0.3"
pulumi = "^3.115.2"
pulumi-aws = "^6.34.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
