version: '3'

env:
  LAMBDA_ROOT: ./infra/lambda
  S3_ROOT: ./infra/s3

tasks:
  clean-lambda:
    cmds:
      - rm -rf $LAMBDA_ROOT
      - mkdir -p $LAMBDA_ROOT
    silent: true

  prep-lambda:
    cmds:
      - task: clean-lambda
      - cp Dockerfile $LAMBDA_ROOT/
      - cp lambda.py $LAMBDA_ROOT/
      - cp -r ./volatility/ $LAMBDA_ROOT/
      - cp api_* $LAMBDA_ROOT/
      - cp io_utils.py $LAMBDA_ROOT/
      - poetry export -f requirements.txt --output $LAMBDA_ROOT/requirements.txt --without-hashes
      - sed -i 's/;.*//g' $LAMBDA_ROOT/requirements.txt
    silent: true

  prep-s3:
    cmds:
      - rm -rf $S3_ROOT
      - mkdir -p $S3_ROOT
      - cp -r ./templates $S3_ROOT/
      - cp -r ./static $S3_ROOT/
      - cp -r ./data $S3_ROOT/
    silent: true

  tests:
    cmds:
      - python -m unittest discover -s tests
    silent: true

  default:
    - task: prep-s3
    - task: prep-lambda
